define(
   ({
    "_widgetLabel": "灾害推演",
       accidentSpotInfo: "事故点综合信息",
       position: "位置信息",
       mediumtype: "介质类型",
       eleva: "高程(m)",
       depofcover: "埋深(m)",
       ishca: "是否高后果区",
       riskgrade: "风险等级",
       pipetype: "钢管类型",
       pipeWeldType: "制管焊缝类型",
       pipeLevel: "管材等级",
       operapressure: "压力(MPa)",
       diameter: "管径(mm)",
       thickness:"壁厚(mm)",
       plumbersName: "管道工姓名",
       plumbersPhone: "管道工电话",
       transmissionName: "巡线员姓名",
       transmissionPhone:"巡线员电话",
       siteName:"名称",
       contactPeople:"联系人",
       mileageValue:"里程值",
       valvenumber:"阀门编号",
       valveFunction:"阀门功能",
       valveType:"阀门类型",
       driveType:"驱动类型",
       autoValve:"自动阀",
       status:"状态",
       boomradius:"爆炸影响范围",
       analysis:"漂管分析",
       query:"查看影响范围",
       calculate:"计算",
       mediumdensity:"输送介质密度(kg/m3)",
       buoyancywaterdensity:"算浮力用的水密度(kg/m3)",
       flowaroundwaterdensity:"算绕流用的水密度(kg/m3)",
       flowrate:"水流速度(m/s)",
       pipeangle:"水流和管道角度(度)",
       yieldstrength:"屈服强度(MPa)",
       modulus:"模量(MPa)",
       inpressure:"内压(MPa)",
       complexload:"重度(-浮力)和阻力复合载荷(N/m)",
       floatlength:"允许悬空长度(m)",
       ultimatefloatlength:"允许极限悬空长度(m)",
       result:"计算结果",
       analysisTip:"允许悬空长度应小于允许极限悬空长度"
  })
);