define({
  "_widgetLabel": "标绘",
  "selectDrawMode": "选择绘制模式",
  "clear": "清除",
  "point": "点",
  "line": "线",
  "polyline": "折线",
  "freehandPolyline": "手绘折线",
  "triangle": "三角形",
  "extent": "包络矩形",
  "circle": "圆形",
  "ellipse": "椭圆",
  "polygon": "面",
  "freehandPolygon": "手绘面",
  "text": "文本",
  "style": "样式",
  "alpha": "透明度",
  "width": "宽度",
  "size": "大小",
  "color": "颜色",
  "markerColor": "标记颜色",
  "outlineColor": "轮廓颜色",
  "lineColor": "线颜色",
  "fillColor": "填充颜色",
  "showMeasurements": "显示测量",
  "areaUnits": "面积单位",
  "distanceUnits": "距离单位",
  "kilometers": "千米",
  "miles": "英里",
  "meters": "米",
  "feet": "英尺",
  "yards": "码",
  "squareKilometers": "平方千米",
  "squareMiles": "平方英里",
  "acres": "英亩",
  "hectares": "公顷",
  "squareMeters": "平方米",
  "squareFeet": "平方英尺",
  "squareYards": "平方码",
  "undo": "撤消",
  "redo": "恢复",
  "results": "结果",
  "points": "点",
  "lines": "线",
  "areas": "面",
  drawLabel:"绘图",
  infoLabel:"查看",
  addLayerLabel:"加载图层",
  queryLabel:"查询",
  featureType0:"无",
  featureType1:"第三方损坏",
  featureType2:"滑坡",
  featureType3:"水毁",
  featureType4:"占压",
  featureName:"标绘名称",
  featureType:"类型",
  featureUnit:"所属单位",
  clearLabel:"删除",
  clearSucc:"删除成功",
  dialogLabel:"是否删除？",
  okLabel:"确定",
  cancelLabel:"取消",
  dialogTitle:"提示",
  shapSave:"图形保存",
  refresh:"刷新",
  noEditTip:"没有权限或不能编辑",
  editSuccess:"编辑成功",
  editFail:"编辑失败",
  property:"属性",
  deleteFail:"删除失败",
  insertSuccess:"插入标绘成功",
  insertFail:"插入标绘失败",
  knownLabel:"知道了",
  editTip:"点击标绘【形状编辑】【移动】【旋转/拉伸】<br>编辑时必须使用【图形保存】，每次只能编辑一个"
});