define(
   ({
        "_widgetLabel": "关键点",
       "allLabel":"全部",
       "startingPointLabel": "起点",
       "needPointLabel":"必到点",
       "specialPointLabel":"特殊点",
       "testPileLabel":"测试桩",
       "patrolPointLabel":"特殊巡点",
       "observationSPointLabel":"特殊观察点",
       "agriculturalRoadLabel":"农路",
       "observationPointLabel":"观察点",
       "keyPointInformationLabel":"关键点信息",
          "department":"部门",
          "pipeline": "管线",
          "marker":"桩号",
          "station":"里程值",
          "radius":"缓冲半径",
          "type":"类别",
          "name":"名称",
          "datatime":"有效日期",
          "lon":"经度",
          "lat":"纬度",
          "describ":"备注",
          "save":"保存",
          "reset":"重置",
          "cancel":"取消",
          "addsuccess":"添加数据成功",
          "editsuccess":"编辑数据成功",
  })
);