define({
  root: ({
    _widgetLabel: "KeyPoint",
    keyworld:"keyworld",
    querycondition:"querycondition",
    query:"query",
    add:"add",
    tip:"tip",
    isdelete:"isdelete?",
    ok:"ok",
    cancel:"cancel",
    name:"name",
    type:"type",
    radius:"radius",
    pipeliename:"pipeliename",
    lon:"lon",
    lat:"lat",
    describ:"describ",
    keypointname:"keypointname",
    position:"position",
    datetime:"datetime",
    buffer:"buffer",
    department:"department",
    edit:"edit",
    delete:"delete",
    deletesuccess:"deletesuccess",
    deletefail:"deletefail"
  }),
  "zh-cn": 1
});