define(
   ({
    "_widgetLabel": "定位",
      classLabel: "查询类别",
      department:"部门",
      noresult:"没查询到结果",
       querylocation: "查询定位",
       pipeline: "管线",
       type: "方式",
       marker: "桩号",
       beginmarker: "起始桩号",
       endmarker: "终止桩号",
       site: "站场",
       beginsite: "起始站场",
       endsite: "终止站场",
       query: "定位",
       rectquery: "拉框查询在线要素",
       pointquery: "点击查询在线要素",
       navgation:"功能导航",
       back:"返回",
       pointselect: "单击选中管段",
       markererror: "中点桩不正确",
       beginmarkererror: "起始桩不正确",
       endmarkererror: "终止桩不正确",
       siteerror: "站场不正确",
       beginsiteerror:"起始站场不正确",
       endsiteerror:"终止站场不正确",
    inmarker: "按桩号",
    insite: "按站场",
    querypoint:"查询点",
    queryline:"查询段"
  })
);