define({
  root: ({
    _widgetLabel: "Inspection",
    personDetail: "Person detail",
    querying: "Querying",
    fullname: "Full name",
    positiontime: "Positiontime",
    speed: "Speed",
    battery: "Battery",
    phone: "Phone",
    department: "Department",
    persontype: "Persontype",
    devicetype: "Devicetype",
    worktime: "Worktime",
    happentime: "Happentime",
    happen:"Happen",
    scope: "Scope",
    keypoints: "Keypoints",
    seepoints: "Seepoints",
    keypointname:"Keypoint Name",
    locationdescription:"Location",
    bufferzone:"Buffer",
    types:"Type",
    totime:"Totime",
    basicInfo:"basicInfo",
    location:"location",
    patrolUnit:"patrolUnit",
    patrolman:"patrolman",
    patrolmode:"patrolmode",
    inspectiontool:"inspectiontool",
    loggingdevices:"loggingdevices",
    inspectionfrequency:"inspectionfrequency",
    inspectiontotallength:"inspectiontotallength",
    currentinspectionpoint:"currentinspectionpoint",
    totalnumberofkeypoints:"totalnumberofkeypoints",
    currentnumberofpatrolsection:"currentnumberofpatrolsection",
    inspectionprogram:"inspectionprogram",
    numbering:"numbering",
    executivedepartment:"executivedepartment",
    inspectionline:"inspectionline",
    inspectiontyp:"inspectiontyp",
    dateRange:"dateRange",
    basisPreparation:"basisPreparation",
    dateofpreparation:"dateofpreparation",
    scanningtask:"scanningtask",
    taskDate:"taskDate",
    scanningtype:"scanningtype",
    pollinglocation:"pollinglocation",
    inspectionrecords:"inspectionrecords",
    inspectiontime:"inspectiontime",
    passrate:"passrate",
    trackPoints:"trackPoints",
    averagespeed:"averagespeed",
    path:"Path",
    pipelengthshouldpatrol:"pipelengthshouldpatrol",
    realTourpipelength:"realTourpipelength",
    skeypoints:"skeypoints",
    rkeypoints:"rkeypoints",
    keypointsInfo:"keypointsInfo"
  }),
  "zh-cn": 1
});