define({
  root: ({
    "_widgetLabel": "Key points",
    "allLabel":"All",
    "startingPointLabel": "StartingPoint",
    "needPointLabel":"NeedPoint",
    "specialPointLabel":"SpecialPoint",
    "testPileLabel":"TestPile",
    "patrolPointLabel":"PatrolPoint",
    "observationSPointLabel":"ObservationSPoint",
    "agriculturalRoadLabel":"AgriculturalRoad",
    "observationPointLabel":"ObservationPoint",
    "keyPointInformationLabel":"KeyPointInformation",
    "department":"department",
    "pipeline": "pipeline",
    "marker":"marker",
    "station":"station",
    "radius":"radius",
    "type":"type",
    "name":"name",
    "datatime":"datatime",
    "lon":"lon",
    "lat":"lat",
    "describ":"describ",
    "save":"save",
    "reset":"reset",
    "cancel":"cancel",
    "addsuccess":"addsuccess",
    "editsuccess":"editsuccess",
  }),
  "zh-cn": 1
});