define(
   ({
    "_widgetLabel": "巡检人员",
       inspectionDate: "巡检日期",
       patrol: "巡检仪",
       total: "总数",
       online: "在线",
       offline: "离线",
       personDetail: "人员详情",
       querying: "正在查询",
       keyPointDetail: "关键点详情",
       name: "名称",
       type: "类型",
       buffer: "缓冲范围",
       pipelinename: "管线名称",
       lon: "经度",
       lat:"纬度",
       describ: "描述",
       fullname: "姓名",
       positiontime: "定位时间",
       speed: "当前速度",
       battery: "电池电量",
       phone: "联系电话",
       department: "所属部门",
       persontype: "人员类型",
       devicetype: "设备类型",
       worktime: "工作时间",
       happentime: "发生时间",
       happen:"发生地点",
       scope: "巡检范围",
       keypoints: "关键点数",
       seepoints: "已巡点数",
       tips:"当日有巡检计划，但暂时未获取人员上报数据",
       traktips: "没有该员工今天的轨迹!",
       nowpersons:"当日巡检人员",
       patrollen: "巡检长度",
       kilometer: "公里",
       positiontip: "没有坐标点，无法定位",
       spendtime: "所用时间",
       nowtime: "当前时间",
       speed:"速度",
       trakplay: "巡检轨迹回放",
       noreach: "尚未到达关键点",
       meter: "米",
       keypoint:"关键点",
       smscontent: "短信内容",
       trak: "轨迹",
       sms: "短信",
       ok: "确定",
       back: "返回",
       success: "发送成功",
       fail:"发送失败",
       all: "全部",
       nodo: "未处理",
       do:"已处理",
       alarmtype:"报警类型",
       alarmperson:"报警人",
       alarm:"紧急报警",
       seeimg:"查看图片",
       endpoint: "设为终点",
       startpoint: "设为起点",
       isearch: "搜索附近",
       inputend: "请输入终点",
       car: "查驾车",
       bus: "查公交",
       inputstart:"请输入起点",
       radius: "半径",
       search: "搜索",
       img:"原图",
       position:"定位",
       devicetrack:"巡检仪轨迹",
       apptrack: "微检APP轨迹",
       play: "回放开始",
       pause:"回放暂停",
       stop:"回放停止",
       noresult:"没查询到结果"
  })
);