define({
  root: ({
    _widgetLabel: "Analysis",
    accidentSpotInfo: "accidentSpotInfo",
    position: "position",
    mediumtype: "mediumtype",
    eleva: "eleva",
    depofcover: "depofcover",
    ishca: "ishca",
    riskgrade: "riskgrade",
    pipetype: "pipetype",
    pipeWeldType: "pipeWeldType",
    pipeLevel: "pipeLevel",
    operapressure: "operapressure",
    diameter: "diameter",
    thickness:"thickness",
    plumbersName: "plumbersName",
    plumbersPhone: "plumbersPhone",
    transmissionName: "transmissionName",
    transmissionPhone:"transmissionPhone",
    boomradius:"boomradius",
    analysis:"analysis",
    query:"Query",
    calculate:"Calculate",
    mediumdensity:"mediumdensity(kg/m3)",
    buoyancywaterdensity:"buoyancywaterdensity(kg/m3)",
    flowaroundwaterdensity:"flowaroundwaterdensity(kg/m3)",
    flowrate:"flowrate(m/s)",
    pipeangle:"pipeangle(°)",
    yieldstrength:"yieldstrength(MPa)",
    modulus:"modulus(MPa)",
    inpressure:"inpressure(MPa)",
    complexload:"complexload(N/m)",
    floatlength:"floatlength(m)",
    ultimatefloatlength:"ultimatefloatlength(m)",
    result:"result",
    analysisTip:"not alow"
  }),
  "zh-cn": 1
});