define(
   ({
    "_widgetLabel": "巡检信息",
       personDetail: "人员详情",
       querying: "正在查询",
       fullname: "姓名",
       positiontime: "定位时间",
       speed: "当前速度",
       battery: "电池电量",
       phone: "联系电话",
       department: "所属部门",
       persontype: "人员类型",
       devicetype: "设备类型",
       worktime: "工作时间",
       happentime: "发生时间",
       happen:"发生地点",
       scope: "巡检范围",
       keypoints: "关键点数",
       seepoints: "已巡点数",
       keypointname:"关键点名称",
       locationdescription:"位置描述",
       bufferzone:"缓冲区范围",
       types:"类型",
       totime:"到位时间",
       basicInfo:"基本信息",
       location:"位置",
        patrolUnit:"巡检单位",
       patrolman:"巡检人员",
        patrolmode:"巡护方式",
        inspectiontool:"巡检工具",
        loggingdevices:"巡检仪",
        inspectionfrequency:"巡检频次",
        inspectiontotallength:"总巡检长度",
        currentinspectionpoint:"当前巡检段",
        totalnumberofkeypoints:"关键点总数",
        currentnumberofpatrolsection:"巡检关键点数",
        inspectionprogram:"巡检计划",
        numbering:"编号",
        executivedepartment:"执行部门",
        inspectionline:"巡检线路",
        inspectiontyp:"巡检类型",
        dateRange:"日期范围",
        basisPreparation:"编制依据",
        dateofpreparation:"编制日期",
        scanningtask:"巡检任务",
        taskDate:"任务日期",
       scanningtype:"巡检类型",
        pollinglocation:"巡检位置",
        inspectionrecords:"巡检记录",
        inspectiontime:"巡线时间",
        passrate:"合格率",
        trackPoints:"轨迹点数",
        averagespeed:"均速(km/h)",
        path:"巡检线路",
        pipelengthshouldpatrol:"应巡管道长度",
        realTourpipelength:"实巡管道长度",
       skeypoints:"应巡关键点数",
        rkeypoints:"实巡关键点数",
       keypointsInfo:"关键点信息"
  })
);