define({
  root: ({
    _widgetLabel: "定位",
    classLabel: "Type",
    department:"Department",
    noresult:"Query no result",
    querylocation: "Querylocation",
    pipeline: "Pipeline",
    type: "Type",
    marker: "Marker",
    beginmarker: "Beginmarker",
    endmarker: "Endmarker",
    site: "Site",
    beginsite: "Beginsite",
    endsite: "Endsite",
    query: "Query",
    rectquery: "Rect query",
    pointquery: "Point query",
    navgation:"Navigation",
    back:"Back",
    pointselect: "Point to select pipeline",
    markererror: "Marker is error",
    beginmarkererror: "Begin marker is error",
    endmarkererror: "End marker is error",
    siteerror: "Site is error",
    beginsiteerror:"Begin site is error",
    endsiteerror:"End site is error",
    inmarker: "Inmarker",
    insite: "Insite",
    querypoint:"Point",
    queryline:"Line"
  }),
  "zh-cn": 1
});