define({
  root: ({
    _widgetLabel: "Monitor",
    inspectionDate: "Date",
    patrol: "Patrol",
    total: "Total",
    online: "Online",
    offline: "Offline",
    personDetail: "Person detail",
    querying: "Querying",
    keyPointDetail: "key point detail",
    name: "Name",
    type: "Type",
    buffer: "Buffer",
    pipelinename: "PipeName",
    lon: "Lon",
    lat:"Lat",
    describ: "Describ",
    fullname: "Full name",
    positiontime: "Positiontime",
    speed: "Speed",
    battery: "Battery",
    phone: "Phone",
    department: "Department",
    persontype: "Persontype",
    devicetype: "Devicetype",
    worktime: "Worktime",
    happentime: "Happentime",
    happen:"Happen",
    scope: "Scope",
    keypoints: "Keypoints",
    seepoints: "Seepoints",
    tips:"Inspection plan, but temporarily did not obtain personnel reported data",
    traktips: "Without the employee's track today!",
    nowpersons: "Nowpersons",
    patrollen: "Patrol length",
    kilometer: "Kilometer",
    positiontip: "No coordinate point, unable to locate",
    spendtime: "Spendtime",
    nowtime: "Nowtime",
    speed:"Speed",
    trakplay: "Trak play",
    noreach: "No reach",
    meter: "meter",
    keypoint:"Keypoint",
    smscontent: "Smscontent",
    trak: "Trak",
    sms: "SMS",
    ok: "Ok",
    back: "Back",
    success: "Success",
    fail:"Fail",
    all: "All",
    nodo: "Nodo",
    do:"Do",
    alarmtype:"Aalarm type",
    alarmperson:"Alarm person",
    alarm:"Alarm",
    seeimg:"See image",
    endpoint: "End point",
    startpoint: "Start point",
    isearch: "Search",
    inputend: "Input end",
    car: "Car",
    bus: "Bus",
    inputstart:"Input start",
    radius: "Radius",
    search: "Search",
    img:"Image",
    position:"Position",
    devicetrack:"Device track",
    apptrack: "APP track",
    play: "Play",
    pause:"Pause",
    stop:"Stop",
    noresult:"Query no result"
  }),
  "zh-cn": 1
});